### ISSUE TITLE
This bug

### ISSUE THREAD

**Issue by provsalt** [Xenophilicy/OreGen#3]
can you take a look at this crash dump and tell me what has happened thanks
PocketMine-MP Crash Dump Sun Feb 3 09:37:54 UTC 2019

Error: mt_rand(): max(0) is smaller than min(1)
File: plugins/OreGen.phar/src/Xenophilicy/OreGen/OreGen
Line: 61
Type: ErrorException

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: OreGen v1.0.1

Code:
[52]             for ($target = 2; $target <= 5; $target++) {
[53]                 $blockSide = $block->getSide($target);
[54]                 if ($blockSide instanceof Water) {
[55]                     $waterPresent = true;
[56]                 }
[57]                 elseif ($blockSide instanceof Lava) {
[58]                     $lavaPresent = true;
[59]                 }
[60]                 if ($waterPresent && $lavaPresent) {
[61]                     $pickBlock = mt_rand(1, $this->config->get("Probability"));
[62]                     switch ($pickBlock) {
[63]                         case 1:
[64]                             if($coal){
[65]                                 $placeBlock = Block::get(Block::COAL_ORE);
[66]                             }
[67]                             else{
[68]                                 $placeBlock = $defaultBlock;
[69]                             }
[70]                             break;
[71]                         case 2:

Backtrace:
#0 (): pocketmine\utils\Utils::errorExceptionHandler(integer 2, string mt_rand(): max(0) is smaller than min(1), string phar:///home/container/plugins/OreGen.phar/src/Xenophilicy/OreGen/OreGen.php, integer 61, array Array())
#1 plugins/OreGen.phar/src/Xenophilicy/OreGen/OreGen(61): mt_rand(integer 1, boolean )
#2 src/pocketmine/plugin/MethodEventExecutor(38): Xenophilicy\OreGen\OreGen->onBlockSet(pocketmine\event\block\BlockUpdateEvent object)
#3 src/pocketmine/plugin/RegisteredListener(98): pocketmine\plugin\MethodEventExecutor->execute(Xenophilicy\OreGen\OreGen object, pocketmine\event\block\BlockUpdateEvent object)
#4 src/pocketmine/event/Event(99): pocketmine\plugin\RegisteredListener->callEvent(pocketmine\event\block\BlockUpdateEvent object)
#5 src/pocketmine/level/Level(1650): pocketmine\event\Event->call()
#6 src/pocketmine/block/Liquid(440): pocketmine\level\Level->setBlock(pocketmine\level\Position object, pocketmine\block\Cobblestone object, boolean 1, boolean 1)
#7 src/pocketmine/block/Lava(89): pocketmine\block\Liquid->liquidCollide(pocketmine\block\Water object, pocketmine\block\Cobblestone object)
#8 src/pocketmine/block/Liquid(217): pocketmine\block\Lava->checkForHarden()
#9 src/pocketmine/level/Level(1655): pocketmine\block\Liquid->onNearbyBlockChange()
#10 src/pocketmine/block/Liquid(309): pocketmine\level\Level->setBlock(pocketmine\level\Position object, CortexPE\block\Lava object, boolean 1, boolean 1)
#11 src/pocketmine/block/Lava(98): pocketmine\block\Liquid->flowIntoBlock(pocketmine\block\Air object, integer 2)
#12 src/pocketmine/block/Liquid(279): pocketmine\block\Lava->flowIntoBlock(pocketmine\block\Air object, integer 2)
#13 src/pocketmine/level/Level(818): pocketmine\block\Liquid->onScheduledUpdate()
#14 src/pocketmine/level/Level(787): pocketmine\level\Level->actuallyDoTick(integer 439)
#15 src/pocketmine/Server(2451): pocketmine\level\Level->doTick(integer 439)
#16 src/pocketmine/Server(2598): pocketmine\Server->checkTickUpdates(integer 439, double 1549186674.0047)
#17 src/pocketmine/Server(2346): pocketmine\Server->tick()
#18 src/pocketmine/Server(2209): pocketmine\Server->tickProcessor()
#19 src/pocketmine/Server(1785): pocketmine\Server->start()
#20 src/pocketmine/PocketMine(249): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/container/, string /home/container/plugins/)
#21 (1): require(string phar:///home/container/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 3.5.9 [Protocol 313]
Git commit: d811217755b78390c739dfd791f2dbf0cf55b0f6
uname -a: Linux 42b1925c-3767-475d-a351-a79e7009bee7 4.15.0-1026-gcp #27~16.04.1-Ubuntu SMP Fri Dec 7 09:59:47 UTC 2018 x86_64
PHP Version: 7.2.13
Zend version: 3.2.0
OS : Linux, linux

Loaded plugins:
KeepInventory 1.0 by KhoaGamingPro for API(s) 3.0.0
MSpawns 2.2 by EvolSoft for API(s) 3.0.0
essentialsTP 1.2.1 by  for API(s) 3.0.0
TopVoter 3.1.0 by SalmonDE for API(s) 3.0.0
VanillaCoordinates 1.0.0 by Shelly7w7 for API(s) 3.0.0
TeaSpoon 1.0.1 by CortexPE for API(s) 3.5.1
MobStacker 1.1.8 by TheWalker0 for API(s) 3.0.0, 4.0.0
AutoInv 0.0.10 by JackNoordhuis for API(s) 3.0.0
ItemCloud 1.3.1 by onebone for API(s) 3.0.0
BlazinVanish 1.0.3 by iiFlamiinBlaze for API(s) 3.0.0
MOTDShuffle 1.1.6 by TheDeibo for API(s) 3.0.2
Worlds 2.0.3 by survanetwork for API(s) 3.0.0
BuilderTools 1.1.0 by CzechPMDevs, VixikCZ for API(s) 3.0.0
MysteryBox 1.0.0 by TheAz928 for API(s) 3.0.0
TimeCommander 1.0.2 by TheDeibo for API(s) 3.0.2
AntiInstaBreak 0.1.2 by dktapps for API(s) 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0
ShadowAntiCheat 3.6.5 by DarkWav for API(s) 3.0.0
BanItem 2.3.3 by LDX for API(s) 3.0.0
InventoryMonitor 1.3.3 by PresentKim for API(s) 3.0.0, 3.0.0-ALPHA12, 4.0.0
OreGen 1.0.1 by Xenophilicy for API(s) 3.0.0
BetterVoting 1.0.2 by Twisted for API(s) 3.2.0
WorldProtect 2.3.8 by aliuly for API(s) 3.0.0
Sheep 5.2.3 by KnownUnown for API(s) 3.0.0
iProtector 1.0.0-BETA by LDX for API(s) 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0
Slapper 1.4.2 by jojoe77777 for API(s) 3.1.0
Broadcaster 1.5 by EvolSoft for API(s) 3.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtPGlz20aWf6WLck2oGYIieIhHVt6SJTnRRoq4phxP7WDK1QSaJCwAjaABUXQq+9v3vdeNi6IO
20rVfrBSsYA+Xr/76G7oj8ZCJiFPP96KRPkyaky6rUbqh6IxsQf9sT06PBz2W42Aq/QsSWTSmPzR
SDcxdDfo/ezOFXGKE1uNUCjFl9gVph8THnnN/QkL+V2zs898xVTIg0AkLF3xiIV+1LT3YdIiC4K3
foCz4hVPJgcHBysZigNXRin3I5EcxEG29CN1cJWIn0TUxlEHKnEP/ikiGa/8wHc3pq8cEiNkA/VL
p8PUABZuTA5tYEXCXXj8V2Ovw5CcWLo3IgXsheNkqR8ox3mPvyYTUWPHz0A+ENv0o1Qsgehui6k0
8aMley5vigkvyZYWyxEC4hhPEr5hx/hvcx+FsWezLwbbPLSRFENVDh6gz6UMBJBDgLsMgZTcM+gf
XIp0Jb2zWxGlZ3fCzVKZNHsjAFhZz3H0Svlv67WM3gQAaibSZlUgAsE4zhz7HIeGvI89ngqCz+T8
k3BTQqf3ADrvxNJXqUiEd4G/gc/N8WhL7Hqo4+xA3Xot6Ek0H0Hf4NFiX4d6fxt1mnpA45rj8QPI
3ifMeu2CzulpX4fJYBuTAOYGBxf4b9M+HHS2cDGQCY5evUlwDrfh0NoHF/7vme81+/1tOLSM49A6
1mslUkKyuWPIVCofrXEnyw2FJ3I+D4RKZSSKYbnqVrSYnNXe8AFU+S1vjrZ5bxbQdFivA/p9IoPA
90Rzx8APwOTky1AlpEaP8q9rDx/AC5AGMayEe/NWJj/zxANjJoDjJwQ7eJxQGf0qeDLfkFhOwKMt
hYZrdx7FtNcZv5ykT2SSirvpWY3cpwVs249I+J4r2CJ8Ecj1eZTK+1iagcd+Kd8iMuh1u48LcTh+
TIjfsnDvMWGP7NFTsp6BBnlZIDztJYyk+49BHY6Gjwqau2kG3mFzKq99oCdHuN8ba+D3HM9MJJC/
NLv9gf0oYO8BgIcPARzcE7nuMXaD0DTZqgq0xTyZgaWyMoVqdzr9oV5s+NBivf7hA4uliLWePXpo
dvee9VRnTxPpQnoG0VWDGT8Axh6OBg+AUSlPUj29e8+Qp/R4CY8ghYcQ+fgR0hfIajI3bb7hSpxA
WqkuJPcecHsmwbqEhOdCLpeVUSY12s6JHuzIsxqNvc2aqCeJAB1ORPPxPKukzLqclvnQTtoxxdpv
/PvPVkP8Ncnyt6e0gJue/tGPbmVwK0KIxgDTA064aSPvhZZiqis9gaQMutDKKj9QOrDmK1CLpUjZ
Eev+yPKX/zhig+LtH//YZ38AnEFvaz7+vCKHMoOQCBD0i/UaJmFLDnv/R5zd3zHbXwACJQRgSsoj
V8gFo2Bq1h3smElrr3HQNBEKM5sjBpopaKnDHRP+xI7hjg4RKPEwHuigDRqjh9AIYMwOLMYPYHHY
eYgTNXr+9rcaZI3Eof0QEjF4CYofgEKukhAeX6UrX4G7k9HCX5Jkmk4DvMmcz0HR0o3T2CfxHHYf
AKzWfuquALliAYNJ74EJ+OOCd2D2BIf1HxmmCW++ciUP9gno4InRmtQAirqcVvo9mSBh5vHk6vji
49W7M03X4RMQSSLDJwahjhB+oy/G75UnFjwLdOpDGI2fgdGw88SgeSI4gRvaT8mhO2n8+b0S/l4J
f6+Ev1fC3yvh75Xw90r4eyX8vRL+Xgk/oxJuNZYYYXmA9WPE8VipUQMDWMyB/vL4qdFrD9pjbM78
wGtM7GG/02r46qMnbhuTBYdEGmrURKbSlQC1Z/dgDZ8q2JFtg4sfDgbz4ag37rjD3thbeMOxveh6
80XHXUBPZ3EIsBN+E/hzmNNp2912B1oyg9yFH2V3rN+d2+PuwLV6w8Oh1R8OPIv3BrbFh2Mx7HTG
cyGGrN+2B+2OZXe6h9bSjdled/i/9mG7A+3W+3kWpRmbXU7Z28Rnp8JlQ9YZTwbjSX/I3l+fsG4H
FPhudPgRChwgaBXD4sN2t2334PWziDxihUYOej9KlWMHDfQS0EtRzytk8S9CxOcRphUy2VR4Xm9v
NUp227QCzyCDSxSm97+sJP+JgziXYCkoQR772N5rd2AovIuIg0UDfliothqeiAFbnAp9Si7S02pD
yGkvoQbUcWroaLXGLQrQf9SPq9n1h6t3F6fQtBZziGZIARJ6OYv5WhNq6MpbqhR12906RWe3MpgB
Yi9FjFkU8C5WN6jPro/fXb+f1hBfpWmswJrW63VbACYItZ3eID3ghoAFPuj09bRCVK25LivQjxpt
L0RRdUXITuvrPymWaxn/JiFhq5BQNFXR77XvKduMB6GMTs9eSjQ5PMfJMSifnkPKbzzyg4CfSJl4
foTRrELUjs4tS7pH3kpA8B6uhy9Fn8oBOs59bCC4UwR5lswEn8US8S5lljdtE1VXuUaeT9ZoGsCo
r6SpzE/rfuAxY8rntO82n8kzyPks5RBXqkpYaayTZLdHdZKuV+IDD2Bg556gWo3+N/mKAocvkc4x
lNDgHyu05C1VQjoomy2N+y9Y61dUiVXmq5fSuk8ANMqBOg4sJ/3oFnLpAqknKTpPRXgSyMyr0FS2
1cXT29Y4qPLm8P9LkWPAOQ6gF7qIgFY9SsKeIgY1EBTQwGiHosio/lM/HBVQke43Af/sR2iralUh
vda8bW+9OvW+/zaA0OlHOOnFmFCHitsbJUb1t2dF5qvr09kqWywCUTXASuu2BR7es8BT4c+3E47u
V9tdufRz/ArS8EEmgVf196ahnlvcE4/KklseiXQtk5sXc/MI03HWhIDjFIg8qZnoGyEbXmXztivD
gypuBwYKKiWm1iK5hnq/Sm+teVteW37m5LNwV9PLU3GLQ3/z7/ybk/95KfJdBB6HkPED8XONVYpY
gWLWcfxShlTQPqiBQh3e4Lbg5o28q6pw2fhErAcNPv487o5eigmhXnku73C7KxHPiup+KE5kGPLI
q6djtfZtQrp/rSnWFn+uMR5DAnqOp2hv8JyiGgjrHfV4aG/T4t2kPI7vBULr+GL687GNYab63s3f
v5ZUsxxExhqWz69wZivuyTXOPlkJnlbo3u6pJ9aH7UGd8FOe3Hzgty+ljAac48yOT+ifpyX4hkcY
4Kv+xbTUHWpv26FenP7zpdAGUOAy9LLPE8IOnwFArMuT6dlBjj+mM3nxeikjP5VVW7vXtZ3cbJFr
jmd/8cMduee2dn5TLnrjAxNivRwkPzmeocbTcXZg/qW8Kok52IZmTS8vp8g7c6+g5Fhx0eDRsqNy
jvRS6vHI0dRzjPWNSMFDQ23pR8uqmlebn/K1azyD8moEdbcIMntez/O1Gh4ofQWJ+ttzKKNUYZpA
1eym2wlR3rxtxVslFQ/8LHgxSWloJiOKNQZfUi9WVPQy85OFLwKvsnFp5Tl8mghxEHKMvAc1ask3
CxHXPDK+V9kwANltWfcvkVxH7/GfF9viwGXBB+Ovqb6r80w7xR2oCiNK1A40KUCjb+itebRK470c
yHpzdn38pP/WHmxYd2ij+ut4y91tu78XD9YUHEravj0+VPiE6hJAKlDLwvKWOhP72z7hk/wkxRB/
amy0v6Gc0At/NYUlRgc5Dej+EgDjkq1UvV+ltU7o4K/dla0sDA6vhsXX7M7ivjpPgCYAQfi2d5x/
ACjLiqS19j/zxKM3z1eIu8Uj5SMpik582uCzgG2pjxuKjb1p8cZO6GIVw5t9TrQ34yl7K+asi4cF
9mDSG+eHBWMn0qAsPz7CnR/4r2iKZZIe2WO713OiUKbeUQ1Vpk+dnGi9AqKtAELEkYyciEeRzCIX
vR/fABTurnyhLwQqGqBwe9sy7hbEeAQrhvzOjFdHPXhfAotC6QnsW8gEoBUtcrFwIuCS50L5ot/i
21g/eP5i4btZkG6ObABCh0SYJCiIVBCk1JET0YGlhWp1pEvXvEkJ4RX9eL/y6PTs7fH7i2sn0opj
/Z5B5XSEylM0JS7gT0vjUzvmSkEw8Y7+Tj/AjCyVluK3gii/9cUaRUm3+I5GTnQHdZiF2kvdAY+W
GV+KIwHRNaLV2qUM8MSmCC3tTRigyBnaHtPX6DKgFU/oUeh0ibImLlADBjWYEixnBuOJYOlKMBmB
xqQrUBIXhZeyOd41dIPMEx48sHvKhrBmMoSZCwSwDVPxhWgxCT2JQpD6VhjbyCwxsPBeIQjTh4iJ
K4Ak8ZoohGIA/KtYF+AOzC01xdYy+iFl6CV4wpCrIRCLV1w2iCHeJtR0r1ciYlm8TLgHANoO6psB
NnEitvdhJRAvlkpYJPIYQDBnmsCCBMwr4JDp6G7CNJCwClAKTyIldnni1ncFW9ENNGwJAbBW0lyC
E0bpFbSrVZZChRVZ5mbuhDkNbTjsnaAT34OThKsVS8Qn6c+RMbFUygflchqI8HEQyDVD66IzVJ1R
sFufs/9GBYEhpCh5rjFhWj/Z3mwF8zjqhpKAp1lfM4gbQCxTIHpwhMB+ovt4eg4j8d4VCLnSYQHC
c6lECf6MDCCHA7xgaI8MlATkgKjON8xID4Ybcyl6SwbtffBBBDICQXLPAzYoLW9EEw/WAR2usoT8
B97kmwvkB4hD/J7xAAW19KEkYLc8yARrmiXBt+0DcL0emKlAO7JAznjKPYFeXPnXLJzjmfeCHatN
5F5zdcNwTwvUto397xVwBA0pJxJHrRIJ/g2UBUarFqPUkRlPA9bXAjaEWA1hgCK2QFTAtjCLQF9x
CMGekTIBPaDSibzzQZ0FsADIITOJCtSQqxqd8wXaBQ5B/W8xP/0BOJcmNMsT6E1JP7fmsiZQkOGF
S+QI0WAZKicEacssOClckkURStFDdyhj4j7tmak2OxW35pmF/nIFbgM1uFU1c6ONyI0kyeJUt2pm
IVNCwEwTRUIFLQMOgT1q0+O30vcA590IoG6gphkzaZfqBWMtPabQLwgtEDaSDRn/T4Gcg85gNGa6
GQwr9FN0IaFY8vkmBV6zmeZyh/iqAy/OvkZxrX3iOekR+Ia1peHkqqWIuoUP+IHfowt5CGUBBUC+
otZskFNG9riUICJ5S3dTfTS6JSFpEWIT1kES2B65+XQFDPb+n6OPedMjyGPg/ibkVSpjWt/45wIf
A00x8BYYh6FeNdjgmjlKdqfb11iRzX8gQzDIqR++HT0yBcIHHQRzM4hsEUQ2pi+uokZLja+2QXT4
xWhx50ISokpyyEtdXZ9N2PXP5zN2cX55fg0+enpxfjZj07N3DBLtX87etRgMYtdXMOqMffj56uKM
Td9dnZzNZu0tk6/xojs41KyYisSXFOrR4yokjq5f5ZwovKoNXIeA4qEnoREWeD2h/SkCgrQTSAQ/
DCqEpD6kYVqzIHHEyBrhMLOUQ8kMwgAfW/prHXRwhSsMFJg90PD2/cGoASbRB3HFwsUkQ7MUcdXy
1HMLAkCpRKxKMnsdQ6fa34mQobqnqV7yZA6mYLkyCHRGi85mJ1fJshAVM4eZOeChQx7RnbwaFpDq
ZaB3eFd9p+IZzdPRc7EASJrSsLS4NrvSnl2rOCQkMgu8AhO8t7iOWIk72jCLCXWg8LDT0USyvbfk
Fe6FQFIWPbugapHIMI+kONf0W1VNrAgVqDCy29aFHQpUVYZZnnWiiBK8+Iv3/7XOelkY6xxN54Gm
3cJ2LZ9THGFGE8aEXo43vEHoBovmO1gKoRgCGoC/BYVSKhNo/ekKpLTM81V0S7hWiVIrF5wO/CYt
RdRo4EPcwdLIXWXRjdJon/AY2/wwCyFu4ukHy0sKlBvTZZRGoGQmmoXhIBnGfXWCTD0mZGgxCxPo
DOJo34joVOqObdWlO8FRDhuH5kai4ZhhFYIoC7BcqAuFIekUMKCsAzJA5BcgpVMFDSLGmw5YnOAM
TVhJFEwjDpoC2SyKQ4tcFXgWYNlgYD4G5jF9cyJz5jnRLh9yq5UMdIY45ymUuZigE64KbwEzEzPI
ZekyyfTqUDEXRa5IsWqvKpS8B11lskkRdotZdkVeKCta1kpzVIxLRz9c5qBU0GIC6Gmaseyh/Bzn
QqPBqc1+hlwOFOeIkjN2Mn3fgrmAwRyMaO17oN4U8skjFuAtAj9hQ5Mwl6m0IsZUhrbZsQcOaMWD
BV500Nm9J0BdzUKwJMNNFdSnirkVIawCq1I/nN2ht8L8kAct7Qpx4Q9+BHUXkAW+RZCXwhz4/TSa
5hl0WUFicYCT1hAcHSwfo9gyr/Va5dLYnfI/i0LCmGnngqVP5Ew6BJm41pdK/OyPu3rSfptNzZwA
v0Y0nyalRSIxpwUXCV8iaSAnoEnFAWUkWJ2aD5piqCCByJPAx/0Vqrbx2i2Uluzy+j0hqoAgpHme
pQyrexJvuZouF9rG04RpZuGkCeGKSu+JebacmALkNd7oBxx0KoYVJnXn1aXSxbjIq07HqB9AQ1Da
NRGsk5WEchI1Mq87RF5QkvvyeMqZ4rfGQ+IWSr6hhF2FbXOIzWD0gqfalQCO+mQjT3WpOgK1oYxD
xZBfUQYSSTfwY0YzgX+XfAO8Qw0J5W1ea6JfJ49IzsnKe/RyqnQM+f5RZZvhmvYJtND1n8LRGyw0
1Eg4U6Yad0HLU3IBZoqlp0xYDFnBrR9QulrTWJe++sjBkSVRIgO0ouXg1WpIykzigVFB5zPIMNyR
wnaTxOR8rDUXGWLH+CUdA/FOdWWxpo2f595fpcW60GHv6hCp294nx6VEFQubmIaQcUPG7AQyAa5a
r4fi08yibaVyv8nLQwfqMmW7wZpvlIZt4FSKQR0ejAvUkpI5M01BESHvg+3Q2spH1fbwdu6OUV17
HMoMXcFCxzDjGVAVDW3IFUQSdylAqfGRgi3be0eRtzKVNCcSujaeCw1qLhZox7SZSjFzldsOmgtt
sdZCuKYcl8kpB2fG+Daasf6OAdYqmF/HsLMTRZ4AHI/2lch8AVEz1QhZY9JDh4BbBlamv+oofauL
IVqLDTe7yo2m81NaiL6LUeTAkIsiQRth+E0kZG6GLKY3V/JcQH/2XSGZ7VmgmntsCUWaKplS7t7k
fGnfZ4xxbGvuUxEHLjYTRh6xjLPAWLB5xshIQ4wzHeFqZA5WrD0gGhx6tQnLc2wyQb1TNdFmh5tq
ZnMQW3VENRLCE9h848MruIWabeGX9fWWwjfVWuMVZKcLWcoAPJKljy7ycSuJoiAk2nEYxm1fEqqR
jDYhVkRgBynuTbqqwBlLPNPNym7Cnbw6Xy4TqKj1blmxD4kpJX4MfLNFGOEGZnp1eoVflFgmTOhA
iQ5hLXQezsFE1rSgIrQL7KmpXdk7h7Bc8FvrIUlkm5cgQt1LqgPJQGSZsFZmltQqKwyD9DxCnahs
W7XAJ8Ur3oJmoB7DeJrnbxCXFiKBjNxC7xJhoNSdJtzqLTBe2wQzh1+VMJxBngrxnhxU7goMPBS1
7s5X2JatJrEq3NQPizhmwjRCxOF5GoWyREeIq9HOnpmTb9+2C/Cmowo/Z+KjaYBxxlqcWv0reyf5
pnbqp5qR+S7JyrSRR8AqyCTaxiXg/jLULx6lm/6igANFClChTy/Qw+QbCOS/AJxxfnnA54EP8Utz
6OyOh3FgXjAjAvyMiCa5rKgLdBT3ribsX5TMQNRq0WbWvxGivpOZpw7VAxWiADPKBP8EBO0d5Mda
tCmwKwJRhkNhUVFCTTUoyMUHRE3OUEGdViUE6InhQRg6egpG5WoT9vbi+HrS/XHYGozv7Fbvrtfq
/mj/6EFo196zifccXPSbR6OOdrL6rT/Y1+mfPqKolO7ajjFaAGvNDhqlYbQFBrJyN0x/0JYlubvN
S5mkOH0gtwJw6C8c4I6Lynll5ecioAGU4+69JX9CK9HwGoyMYr75SyaVFouSznax1SfpbxAwcQe+
TZkC0L3BekFRxQPs0H/HQm8L0Diklv6CR6DjAxmJJpGgQ1KRFK640WqIu1REqD10mZbuala+5UKj
rb6D6COlgmpT7NanqN8BI9GrfRGmv1cr3ucupJiragsefkUeT2ptySZOJV2N1JfqXfPnaMoRWVJD
5ZMyp/WHdP9s4Qd0vF8OWKS1L9WWXu0trHWuOF56N5+YYR7m4Sl5ZcBselF9JYX39Hd5+kuncK6P
/Kqjwg3wh76PM09sgLfFuniowCw8Kx90+p0hPL46x52x0ULwbn/RHfWHCz4c2ONOx54L/EBwPOKi
w12+EL3RkL0iSURpjR/TFXG0a65ulbHpI2Ub9F2muXpKX+pJ5d/VRGt288znT0P8irHVeCcWZkem
JvZVKGv8U7SaqmmTMt+B4f15fzn3I44f+hGCeKEmlTcigkSmJrMNpzNoHIMfG372Y32pe0CvxEW/
HP/nn/8HkO1R2w==
===END CRASH DUMP===

**Comment by provsalt** [comment]
i have defult settings also if there is a new release to fix this i will be glad to download it

**Comment by Xenophilicy** [comment]
Hello, thanks for reporting this. Please download the latest version from [Poggit v1.1.3](https://poggit.pmmp.io/p/OreGen/1.1.3) and try again. You will also need to delete your data folder for OreGen in `plugin_data` and enter your settings in the new config file. Let me know if you have any further issues!

**Comment by Xenophilicy** [comment]
@provsnoobgaming,

Please close the issue if and when your problem has been solved, thanks!

**Comment by Xenophilicy** [comment]
Issue resolved in later update available on [Poggit](https://poggit.pmmp.io/p/OreGen).
