### ISSUE TITLE
Suggestion - Customizable Gen

### ISSUE THREAD

**Issue by BroCrows** [Xenophilicy/OreGen#5]
Can you make it where we can customize the blocks that spawn. What you can do with the config is...
(Normal Config)
Custom Ore Spawn:
- id: (id)
  probability: (Chance of spawn)

**Comment by Xenophilicy** [comment]
Hello, thanks for your suggestion. I will try to get this updated feature added as soon as I can!

**Comment by Xenophilicy** [comment]
I have pushed update v1.2.0 for this feature request to Poggit and can be downloaded [here](https://poggit.pmmp.io/p/OreGen/1.2.0)!

Thanks for your suggestion and enjoy the new feature!
