### ISSUE TITLE
Skyblock support

### ISSUE THREAD

**Issue by feanboy** [Xenophilicy/OreGen#7]
Im using 2 plugins
1 OreGen
2 SkyBlock by GiantQuartz
And now i want that skyblock worlds are automaticly being added to the worlds of OreGen
But idk how

**Comment by Xenophilicy** [comment]
I'll put this on my list of things to do, thanks for opening an issue here 👍

**Comment by Xenophilicy** [comment]
I was clearly very tired when reading this issue, simply list the worlds you don't want OreGen to work in and every other world will be allowed to use the plugin. That is why there is a blacklist option.
